name: PublishBetaZip

on:
  push:
    branches:
      - beta

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build the zip file
      run: |
        python build.py
    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-1.3
      with:
        # The pattern of files to upload
        args: install/*.zip
